name: Deploy to Firebase

on:
  push:
    branches:
      - flutterflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Update package name
        run: |
          sed -i 's/name: .*/name: com.goappy.journeyforward/' pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Clean build cache
        run: flutter clean

      - name: Build Flutter Web
        run: flutter build web --no-tree-shake-icons

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create firebase.json
        run: |
          echo '{
            "hosting": {
              "public": "build/web",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ]
            }
          }' > firebase.json

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project yourcaio-c75b4 --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
