name: Deploy to Firebase CAIO a

on:
  push:
    branches:
      - manuallyPushed
      - main
      - flutterflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Update intl package version
        run: |
          sed -i 's/intl: 0.18.0/intl: ^0.18.1/' pubspec.yaml
      - name: Upgrade Dependencies
        run: flutter pub upgrade

      - name: Build Flutter Web
        run: flutter build web --no-tree-shake-icons

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

        
      - name: Add redirect to index.html
        run: |
          echo '
          <script>
            document.addEventListener("DOMContentLoaded", function() {
              switch (window.location.hostname) {
                case "mabm.app":
                  console.log("Redirecting for mabm.app");
                  window.location.href = "/library?companiesDoc=0fXG0CVY9h92MABM";
                  break;
                case "journeyforward.app":
                  console.log("Redirecting for journeyforward.app");
                  window.location.href = "/library?companiesDoc=0fXG0CVY9h92MjpurneyForward";
                  break;
                default:
                  console.log("Hostname does not match any known hosts");
                  break;
              }
            });
          </script>
          ' >> build/web/index.html

          
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project yourcaio-c75b4 --token ${{ secrets.FIREBASE_TOKEN }}

        
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
