name: Firebase Deployment

on:
  push:
    branches:
      - flutterflow  # This is the branch where FlutterFlow commits
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.0'  # Using Flutter version 3.13.0

      - name: Update intl package version
        run: |
          sed -i 's/intl: 0.18.0/intl: ^0.18.1/' pubspec.yaml
      - name: Upgrade Dependencies
        run: flutter pub upgrade

      - name: Build Flutter Web
        run: flutter build web --no-tree-shake-icons

      - name: Create firebase.json
        run: |
          echo '{
            "hosting": {
              "public": "build/web",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ]
            }
          }' > firebase.json
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.6.2
        with:
          args: deploy --only hosting --project yourcaio-c75b4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
