name: Firebase Deployment

on:
  push:
    branches:
      - flutterflow  # This is the branch where FlutterFlow commits
      - main
      - manuallyPushed  # Include this line to trigger the workflow on changes to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        # No version specified; it will use the latest stable version by default

      - name: Update intl package version
        run: |
          sed -i 's/intl: 0.18.0/intl: ^0.18.1/' pubspec.yaml
      - name: Upgrade Dependencies
        run: flutter pub upgrade

      - name: Build Flutter Web
        run: flutter build web --no-tree-shake-icons

      - name: Create firebase.json
        run: |
          echo "{
            \"hosting\": {
              \"public\": \"build/web\",
              \"ignore\": [
                \"firebase.json\",
                \"**/.*\",
                \"**/node_modules/**\"
              ],
              \"rewrites\": [
                {
                  \"source\": \"/\",
                  \"function\": \"redirectUrl\"
                },
                {
                  \"source\": \"**\",
                  \"destination\": \"/index.html\"
                }
              ]
            }
          }" > firebase.json
        working-directory: .  # This sets the working directory to the project root

      - name: List files in root
        run: ls -la
        working-directory: .  # Adjust if necessary to target the intended directory
      

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project yourcaio-c75b4 --token ${{ secrets.FIREBASE_TOKEN }}
        
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
