name: Flutter CI/CD 2

on:
  push:
    branches:
      - flutterflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # This is the Eclipse Temurin distribution, which is recommended
        java-version: '11'

        
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Build iOS
      run: |
        cd ios
        flutter build ios --release --no-codesign
