name: Flutter CI/CD 2

on:
  push:
    branches:
      - flutterflow-COMMENACKTTHIS 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Cache dependencies
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
   
    - name: Setup Flutter
      uses: subosito/flutter-action@v1

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

  build-ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/CocoaPods
          ios/Pods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-cocoapods-
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v1

    - name: Get dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install Pods
      run: cd ios && pod install

    - name: Build iOS
      run: flutter build ios --release --no-codesign
