name: Flutter CI/CD 2

on:
  push:
    branches:
      - flutterflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
   
    - name: Setup Flutter
      uses: subosito/flutter-action@v1

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

  build-ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v1

    - name: Get dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install Pods
      run: cd ios && pod install

    - name: Build iOS
      run: flutter build ios --release --no-codesign
