name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - flutterflow # Adjust this as necessary for your workflow

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.3' # Specify your Flutter version here
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
  
  build-ios:
    name: Build iOS
    needs: build-android # Ensures iOS build starts only after Android build completes
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.3' # Ensure this matches the Flutter version used in Android build
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      
      - name: Install Pods
        run: |
          cd ios
          pod install
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
